name: build
on:
  schedule:
  - cron:  '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: docker
      run: |
        docker build -t ci-pendulum .
